# Generated by Django 5.2.16 on 2026-07-08 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('project', 'Proyecto'), ('inverter', 'Inversor'), ('dc_string', 'DC / strings'), ('meter', 'Medidores'), ('data', 'Datos'), ('weather', 'Meteo'), ('grid', 'Red / MT'), ('power_quality', 'Calidad energía'), ('om', 'Gestión O&M')], max_length=20)),
                ('component_type', models.CharField(choices=[('project', 'Proyecto'), ('inverter', 'Inversor'), ('string', 'String'), ('meter', 'Medidor'), ('weather_station', 'Estación meteo'), ('relay', 'Reconectador')], max_length=20)),
                ('default_severity', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('default_params', models.JSONField(blank=True, default=dict)),
                ('rule_group', models.CharField(choices=[('fast', 'Cada 5 min'), ('hourly', 'Cada hora')], default='fast', max_length=10)),
                ('auto_resolve', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('project', 'Proyecto'), ('inverter', 'Inversor'), ('string', 'String'), ('meter', 'Medidor'), ('weather_station', 'Estación meteo'), ('relay', 'Reconectador')], max_length=20)),
                ('component_id', models.CharField(blank=True, default='', max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('acknowledged', 'Reconocida'), ('resolved', 'Resuelta')], db_index=True, default='active', max_length=15)),
                ('dedup_key', models.CharField(max_length=255)),
                ('triggered_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.EmailField(blank=True, default='', max_length=254)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_type', models.CharField(blank=True, choices=[('auto', 'Automática'), ('manual', 'Manual')], default='', max_length=10)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('last_evidence', models.JSONField(blank=True, default=dict)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('inverter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alarms', to='plants.inverter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarms', to='plants.project')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarms', to='alarms.alarmrule')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'status'], name='alarms_alar_project_e70f94_idx'), models.Index(fields=['rule', 'status'], name='alarms_alar_rule_id_f2b665_idx'), models.Index(fields=['status', 'severity', 'triggered_at'], name='alarms_alar_status_b46937_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'resolved'), _negated=True), fields=('dedup_key',), name='uniq_open_alarm_per_dedup_key')],
            },
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_group', models.CharField(choices=[('fast', 'Cada 5 min'), ('hourly', 'Cada hora')], max_length=10)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'OK'), ('partial', 'Parcial (alguna regla falló)'), ('failed', 'Falló')], max_length=10)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', '-started_at'], name='alarms_eval_project_10f340_idx')],
            },
        ),
        migrations.CreateModel(
            name='NonComputableInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('pr', 'Performance ratio'), ('availability', 'Disponibilidad')], max_length=20)),
                ('interval_start', models.DateTimeField()),
                ('interval_end', models.DateTimeField()),
                ('missing_inputs', models.JSONField(blank=True, default=list)),
                ('inverter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.inverter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('inverter__isnull', False)), fields=('project', 'inverter', 'metric', 'interval_start'), name='uniq_noncomputable_inverter'), models.UniqueConstraint(condition=models.Q(('inverter__isnull', True)), fields=('project', 'metric', 'interval_start'), name='uniq_noncomputable_project')],
            },
        ),
        migrations.CreateModel(
            name='RuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(blank=True, help_text='Vacío = hereda del catálogo', null=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_configs', to='plants.project')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='alarms.alarmrule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rule', 'project'), name='uniq_ruleconfig')],
            },
        ),
    ]
