# Generated by Django 5.2.16 on 2026-08-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0013_meter_day_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='maintenance_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarm',
            name='maintenance_started_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('acknowledged', 'Reconocida'), ('in_maintenance', 'En mantenimiento'), ('resolved', 'Resuelta')], db_index=True, default='active', max_length=15),
        ),
        migrations.CreateModel(
            name='AlarmStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('active', 'Activa'), ('acknowledged', 'Reconocida'), ('in_maintenance', 'En mantenimiento'), ('resolved', 'Resuelta')], max_length=20)),
                ('to_status', models.CharField(choices=[('active', 'Activa'), ('acknowledged', 'Reconocida'), ('in_maintenance', 'En mantenimiento'), ('resolved', 'Resuelta')], max_length=20)),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='alarms.alarm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
