# Generated by Django 5.2.16 on 2026-07-08 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('plant_code', models.CharField(blank=True, default='', max_length=100)),
                ('weather_plant_code', models.CharField(blank=True, default='', max_length=100)),
                ('installed_capacity_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(default='America/Bogota', max_length=64)),
                ('is_minifarm', models.BooleanField(default=False)),
                ('monitoring_enabled', models.BooleanField(default=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField()),
                ('dev_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverters', to='plants.project')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(blank=True, default='', max_length=20)),
                ('component_id', models.CharField(blank=True, default='', max_length=100)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True, default='')),
                ('created_by', models.EmailField(blank=True, default='', max_length=254)),
                ('inverter', models.ForeignKey(blank=True, help_text='Vacío = aplica a todo el proyecto', null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.inverter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to='plants.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'starts_at', 'ends_at'], name='plants_main_project_14d53e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='inverter',
            constraint=models.UniqueConstraint(fields=('project', 'external_id'), name='uniq_inverter_per_project'),
        ),
    ]
