# Generated by Django 5.2.16 on 2026-07-09 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InverterStateObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('times_seen', models.PositiveIntegerField(default=1, help_text='Avistamientos acumulados (inversor × tick)')),
                ('first_dev_name', models.CharField(blank=True, default='', max_length=200)),
                ('first_project', models.ForeignKey(blank=True, help_text='Proyecto donde se observó por primera vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='plants.project')),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
