# Generated by Django 5.2.16 on 2026-07-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_inverterstateobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_self_consumption',
            field=models.BooleanField(default=False),
        ),
    ]
