# Generated by Django 5.2.16 on 2026-07-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_project_is_self_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ignore_weather_station',
            field=models.BooleanField(default=False),
        ),
    ]
