# Generated by Django 5.2.16 on 2026-07-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_project_ignore_weather_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='discord_thread_id',
            field=models.CharField(blank=True, default='', help_text='ID del hilo de Discord del proyecto (?thread_id=). Vacío = canal raíz', max_length=50),
        ),
    ]
