# Generated by Django 5.2.16 on 2026-08-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_project_discord_thread_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('whatsapp_group_id', models.CharField(blank=True, help_text='ID del grupo creado/habilitado en WhatsApp Groups API.', max_length=255, null=True, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Zona operativa cuyo grupo de WhatsApp recibe las alarmas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='plants.zone'),
        ),
    ]
