# Generated by Django 5.2.16 on 2026-07-08 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alarms', '0002_seed_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('discord', 'Discord'), ('gmail', 'Gmail')], max_length=20)),
                ('env_key', models.CharField(default='webhook_discord', help_text='Nombre de la variable del .env con el secreto (webhook/credencial)', max_length=100)),
                ('discord_channel_id', models.CharField(blank=True, default='', help_text='Cacheado con GET al webhook; snapshot en cada NotificationLog', max_length=50)),
                ('recipients', models.TextField(blank=True, default='', help_text='Solo gmail: correos separados por coma')),
                ('min_severity', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='medium', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('opened', 'Abierta'), ('escalated', 'Escalada'), ('resolved', 'Resuelta'), ('sla_reminder', 'Recordatorio SLA')], max_length=15)),
                ('target_channel_id', models.CharField(blank=True, default='', help_text='Snapshot del channel ID de Discord al momento del envío (trazabilidad)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('failed', 'Fallida')], default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alarms.alarm')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.notificationchannel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('event', 'sla_reminder'), _negated=True), fields=('alarm', 'channel', 'event'), name='uniq_notification_per_event')],
            },
        ),
    ]
