# Generated by Django 5.2.16 on 2026-08-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_default_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('group_id', models.CharField(db_index=True, max_length=255)),
                ('sender_id', models.CharField(blank=True, default='', max_length=100)),
                ('text', models.TextField(blank=True, default='')),
                ('response_text', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='destination_group_id',
            field=models.CharField(blank=True, default='', help_text='Solo resumen general: ID del grupo de WhatsApp de destino.', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='purpose',
            field=models.CharField(choices=[('realtime', 'Alarmas por zona en tiempo real'), ('general_summary', 'Resumen general bajo demanda')], default='realtime', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, default='', help_text='ID del número de WhatsApp Business que realiza los envíos.', max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='kind',
            field=models.CharField(choices=[('discord', 'Discord'), ('whatsapp', 'WhatsApp'), ('gmail', 'Gmail')], max_length=20),
        ),
    ]
