# Generated by Django 5.2.16 on 2026-08-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_seed_whatsapp_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='target_channel_id',
            field=models.CharField(blank=True, default='', help_text='Snapshot del ID de destino al momento del envío (trazabilidad)', max_length=255),
        ),
    ]
